feat: init project FE
rada-network/nft4charity pull request #35
Opened 2021-10-04 14:39 UTC by damminhtien

+ Init base project
![image](https://user-images.githubusercontent.com/25586408/135871071-0a3d6c53-0895-495a-89e9-3b64bf40bfd7.png)

+ Simple register page
![image](https://user-images.githubusercontent.com/25586408/135871002-6085e079-9121-40c5-8e8a-0e23a01b317c.png)

+ Simple login page
![image](https://user-images.githubusercontent.com/25586408/135871154-7a868151-1da6-4ee3-a865-fcd57fc0963d.png)

## Summary
+ Init base project with Typescript and Tailwind

## How was it tested? Tested - Work well

## Anything else?

2021-10-05 18:00 UTC, coleslaw requested changes
accidentally deleted code. Please revert them. 

Can you add a screenshot of the homepage to PR description?

2021-10-05 18:00 UTC, coleslaw commented on README.md
> -# Description
why delete?

2021-10-06 00:55 UTC, damminhtien commented
@coleslaw It was a mistake of my teammate. He pushed code to my branch. I reverted to the commit of mine - the initial codebase of FE. 
We will push the homepage commit after this one is merged.

2021-10-06 13:44 UTC, coleslaw approved these changes
nice job @damminhtien

2021-10-06 13:45 UTC, merged